### ISSUE TITLE
Block Diagram missing Business layer

### ISSUE THREAD

**Issue by vakhil-98** [anees1203/BWorks-Material-Donation-Tracking#1]
@anees1203 It would improve the understanding of people if the block diagram includes business layer part in the it.

**Comment by anees1203** [comment]
Can you tell me in detail what you mean by Business layer?

**Comment by vakhil-98** [comment]
I mean whenever data is sent from front end, how is it received in database?
It's received via business layer. 
By mentioning business layer in the block diagram, it would enhance viewer's understanding of the diagram.

**Comment by anees1203** [comment]
okay I will work on that
